apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-test-apps
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
patches:
  - patch: |
      - op: add
        path: /metadata/annotations
        value:
          "downscaler/force-downtime": "true"
    target:
      kind: Deployment
      name: demoapp-caas-demoapp
