apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: demoapp
  namespace: flux-test-apps
spec:
  releaseName: demoapp
  chart:
    spec:
      chart: caas-demoapp
      sourceRef:
        kind: HelmRepository
        name: caas-charts
  interval: 1m
  install:
    remediation:
      retries: 3
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: demoapp-caas-demoapp
            patch: |
              - op: add
                path: /metadata/annotations
                value:
                  "downscaler/force-downtime": "true"
