apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubedownscaler
  namespace: kubedownscaler
spec:
  releaseName: kubedownscaler
  chart:
    spec:
      chart: kubedownscaler
      sourceRef:
        kind: HelmRepository
        name: kubedownscaler
  interval: 1m
  install:
    remediation:
      retries: 3
  values:
