apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubedownscaler
  namespace: kubedownscaler
spec:
  type: oci
  interval: 1m
  url: oci://mtr.devops.telekom.de/caas/charts/go-kube-downscaler
