apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  releaseName: argocd
  chart:
    spec:
      chart: argo-cd
      sourceRef:
        kind: HelmRepository
        name: argo-helm
  interval: 1m
  install:
    remediation:
      retries: 3
  values:
