apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/kubedownscaler
  - ../base/demoapp
patches:
  - path: kubedownscaler-values.yaml
    target:
      name: kubedownscaler
      namespace: kubedownscaler
      kind: HelmRelease
